# Generated by Django 5.0.6 on 2024-06-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='file',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='file_1',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='file_2',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='file_3',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='file_4',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, upload_to='images/%Y/%m/%d/'),
        ),
    ]
