# Generated by Django 5.0.6 on 2024-06-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_remove_advertisement_file_advertisement_file_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файлы'),
        ),
    ]
