# Generated by Django 5.0.6 on 2024-06-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.message', verbose_name='Отклики'),
        ),
    ]
