# Generated by Django 5.0.6 on 2024-06-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_advertisement_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.author'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить файл'),
        ),
    ]
