# Generated by Django 5.0.6 on 2024-06-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='file_4',
            new_name='header_image',
        ),
    ]
