# Generated by Django 5.0.6 on 2024-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_rename_file_4_advertisement_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Прикрепить фото поста'),
        ),
    ]
