# Generated by Django 5.0.6 on 2024-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_advertisement_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/no_avatar.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
