# Generated by Django 5.0.6 on 2024-06-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_alter_author_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted_users', to='advertisement.author', verbose_name='Отклики'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='advertisement.author'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slots',
            field=models.PositiveIntegerField(default=1, verbose_name='Слотов доступно'),
        ),
    ]
