# Generated by Django 5.0.6 on 2024-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_advertisement_accepted_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, related_name='accepted_users', to='advertisement.author', verbose_name='Участники'),
        ),
    ]
