# Generated by Django 5.0.6 on 2024-06-27 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_alter_advertisement_accepted_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='advertisement.message', verbose_name='Отклики'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=64, verbose_name='Текст'),
        ),
    ]
