# Generated by Django 5.0.6 on 2024-06-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_alter_advertisement_response_alter_message_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='response',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='response',
            field=models.ManyToManyField(blank=True, null=True, related_name='responses', to='advertisement.message', verbose_name='Отклики'),
        ),
    ]
