# Generated by Django 5.0.6 on 2024-07-01 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_message_creation_date_alter_advertisement_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='accepted_users',
            new_name='accepted_authors',
        ),
    ]
