# Generated by Django 5.0.6 on 2024-07-03 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_rename_accepted_users_advertisement_accepted_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='views',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='wiewers',
            field=models.ManyToManyField(related_name='viewers', to='advertisement.author', verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='advertisement.author', verbose_name='Автор'),
        ),
    ]
