# Generated by Django 5.0.6 on 2024-07-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_rename_wiewers_advertisement_wievers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='wievers',
            new_name='viewers',
        ),
    ]
