# Generated by Django 5.0.6 on 2024-07-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0019_rename_wievers_advertisement_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='advertisement.author', verbose_name='Просмотры'),
        ),
    ]
