# Generated by Django 5.0.6 on 2024-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0020_alter_advertisement_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл 1'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл 2'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл 3'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
