# Generated by Django 5.0.6 on 2024-07-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0022_remove_author_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='fifst_name',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/no_avatar.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
