# Generated by Django 5.0.6 on 2024-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0024_rename_fifst_name_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='state',
            field=models.CharField(choices=[('IN', 'In Progress'), ('UN', 'Unfinished'), ('FI', 'Finished')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='body',
            field=models.TextField(max_length=300, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='header',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
