# Generated by Django 5.0.6 on 2024-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0027_remove_advertisement_disliked_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
