# Generated by Django 5.0.6 on 2024-07-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0028_advertisement_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
