# Generated by Django 5.0.6 on 2024-07-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='to',
            new_name='user_to',
        ),
    ]
