# Generated by Django 5.0.6 on 2024-07-09 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_to_chat_user_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='MyChat',
        ),
    ]
