# Generated by Django 5.0.6 on 2024-07-12 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_mychat_user_to_mychat_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mychat',
            name='chat_name',
            field=models.CharField(default=1, max_length=32, verbose_name='Чат для объявления:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mychat',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
